[project]
name = "phonikud"
version = "0.1.0"
description = "Hebrew nakdan with Shva Na and Atama'a"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["torch>=2.6.0", "transformers>=4.51.3"]
